### ISSUE TITLE
Prerequisite of Join & Translation Progress

### ISSUE THREAD

**Issue by linbudu599** [blitz-js/zh-hans.blitzjs.com#3]
**Looking for translators, you need to possess related develop experience including but not limited to:**

- GraphQL
- NextJS
- Prisma
- BlitzJS

**Translation Progress:**

- [x] Home Page
- [x] Get Started
- [x] Tutorial

**Comment by esmadrider** [comment]
Prerequisite  & Translation progress now all in #1 , closed now 🥸
